### ISSUE TITLE
Clean Growth Discovery

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-obps#139]

**Comment by jaimiebutton** [comment]
Hey @nanyangpro I've created this epic for us to add tickets to when we're ready!

**Comment by nanyangpro** [comment]
Wonderful, thanks @jaimiebutton! Now that the Internal Discovery Plan is almost completed, I'll start to add tickets required here following the plan (#111, #112, #113, #114) in the next few days. Once created, I'll pin you for review. :)

**Comment by patriciarussellCAS** [comment]
All issues have been completed in this Epic. Will close this and we can create a new one if this is needed in the future.
