### ISSUE TITLE
Explore other government reporting systems

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-obps#185]
Are their other Provincial emissions reporting systems that are similar to BC's that would be worth getting familiar with and comparing to? Does the business area have connections with other jurisdictions that could help in this exploration?

**Acceptance Criteria:**
- [x] Reach out to the program area to see if they have any recommendations
- [x] Make note of any provincial or federal systems that are similar to BC-ERS
- [x] Make note of any private sector emissions reporting platforms
- [x] Take screenshots of what is available
- [x]  Note any demos to set up in the future for any applicable platforms that are not publicly available

**Goal of this ticket:**
Let's not start from scratch with what we build! It's highly likely many elements of our new system have been done before.

**Comment by pbastia** [comment]
MS will setup something with AB

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-obps/185?planning-poker) with Zenhub @NicoleGovvy

**Comment by jaimiebutton** [comment]
Results can be found in the Reporting Miro board under 'Environmental Scan'

**Comment by patriciarussellCAS** [comment]
Do we want to keep this ticket open in case we get demos from other systems? @jaimiebutton
