### ISSUE TITLE
Multiple apps for one CSS Integration

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-obps#211]
We probably want one CSS integration to apply to multiple apps since the set of users will be the same. For our other integrations we have had a 1-1 relationship app to instance. Explore if this requires any extra setup.

**Comment by dleard** [comment]
It was for reporting, to check if there were any extra steps needed for separate apps (registration + reporting) using the same css integration. I looked into it and it shouldn't need any extra setup. I'll close this ticket.
