### ISSUE TITLE
High-level plan for Reporting discovery

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-obps#218]
We'll soon be starting exploratory discovery for reporting (aka BC-ERS). This ticket captures some initial thinking to plan for that discovery when it comes. 

Acceptance Criteria:
- [x] Brainstorm goals of discovery
- [x] Brainstorm ideal outcomes/outputs of a discovery phase
- [x] Ideate potential discovery activities
- [x] Pass to scrum team for feedback + iterate on feedback if necessary

Goal of this ticket:
- Be able to answer the question of "what will discovery be like for reporting?"

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/218?planning-poker) with Zenhub @nanyangpro @NicoleGovvy

**Comment by jaimiebutton** [comment]
Hey @NicoleGovvy , is there anything else this ticket needs before closing?

**Comment by NicoleGovvy** [comment]
@jaimiebutton were you wanting more team feedback? If not then yes this can be closed.
