### ISSUE TITLE
Create sample org/facility 'personas' 

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-obps#226]
#### Describe the task

Create sample operation/facility structures based on real structures we expect to register in OBPS to help DTS team in designing and building OBPS systems.

#### Acceptance Criteria

- [x] Connect with business area (PO?) to understand possible structures
- [x] Document structures
- [x] Post them in the registration DST board (or other appropriate Miro board)

**Comment by NicoleGovvy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/226?planning-poker) with Zenhub @NicoleGovvy @nanyangpro @jaimiebutton

**Comment by NicoleGovvy** [comment]
Hanna has created a couple structures, ticket can be closed.

**Comment by patriciarussellCAS** [comment]
@hannavovk this ticket looks like it can be closed.

**Comment by hannavovk** [comment]
@patriciarussellCAS Yes, makes sense. Closing now.
