### ISSUE TITLE
Confirm external user roles for reg & reporting

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-obps#240]
We have a starter set of user roles & permissions for external BCEIRS users, however we need a clear picture of how users will flow within the system, from module to module.

- [x]  Review current roles & permissions chart
- [x]  Review external user roles & permissions with external users during research sessions
- [x]  Update roles in Miro
- [x] Review with POs/teams

Outcome: user roles & permissions for registration and reporting modules, possibly COAM

**Comment by patriciarussellCAS** [comment]
This looks good to me. If we need further exploration for external user access for COAM that can happen separately.
