### ISSUE TITLE
COAM Service Design Plan: to make a plan

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-obps#241]
To kick off our work on COAM, we'd like to get our initial discovery planning planned.

This will include:

- [x]  Identifying activities we want to undertake for planning and where they fall on the timeline and noting them on the Miro board
- [x]  Create planning artefact
- [x]  Share with POs for feedback 
- [ ]  Make any updates needed
- [x] Booking session for CATS demo
- [x] Booking session for offsets registry demo

**Comment by zoeyli-46** [comment]
@hannavovk I pulled this into current sprint, since this is a Goose goal but it lives on our board currently

@patriciarussellCAS are you guys able to see this on Giraffe board?

**Comment by NicoleGovvy** [comment]
@zoeyli-46 no we aren't. I've added the Giraffe tag so we can find it more easily on the Moose board.

**Comment by NicoleGovvy** [comment]
Emailed CATS contact April 9 to request a demo.
