### ISSUE TITLE
Investigate options for metrics software

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-obps#242]
We would like to discover and document what options exist for metrics software within BCIERS, understand what they are, and have these documented to help make a decision about what would be most appropriate.

- [x] Document Snowplow vanilla functionality (what's available in the CIIP instance)
- [x] Explore government ecosystem to identify any teams using other options
- [ ] Document options, features/limitations in Miro
- [ ] Share with POs/team/SMEs

The goal of this ticket is to capture the options available to help us as we start to work through identifying and implementing metrics to support business area goals and measure the user experience.

**Comment by rdromey** [comment]
Potential to explore Sentri functionality as well

**Comment by NicoleGovvy** [comment]
Include Century as part of investigation.

**Comment by NicoleGovvy** [comment]
@patriciarussellCAS the more I started digging into this the more it seems like we need more answers about what we want metrics to do as there's a few options. I'll add options/some features to the metrics Miro board, but otherwise I think this can be closed for now.

**Comment by rdromey** [comment]
Closed as is with current work completed and rolled forward into ticket bcgov/cas-coam#5   for future discussion
