### ISSUE TITLE
Move the registration client into the nx bciers monorepo

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-obps#257]
Giraffe has added nx.dev and the reporting client already lives in there. The registration client should also be moved into the bciers monorepo & be configured to run from there. This should allow us to start better defining shared components and fix some things that got wonky after the merge of giraffe-develop to develop (like having multiple eslint instances).

AC Checklist:
- [x] The registration frontend lives under bciers in a "registration" directory
- [x] The registration frontend builds properly using nx
- [x] The registration tests still run properly
  - [ ] A 🫎 dev should do manual testing as well
- [x] A single eslint instance is used by both reporting & registration & pre-commit passes
- [x] Documentation is updated if necessary (any changes on how to run the registration app, updates to the nx monorepo docs, etc)
- [ ] Add local migration documentation
- [ ] Pull a release before and after this merge

**Comment by mikevespi** [comment]
From discussion during refinement:
- Consider which is the better approach between just dragging and dropping the Registration code into the BCIERS apps and then telling Nx about it, or using Nx to generate a new app and copy the Registration code base into that
- Be mindful of the git history between the two approaches. Git may not view the latter of the above approaches as a moved file
- After the migration, ahve a Moose do some manual QA testing

**Comment by hannavovk** [comment]
Next step - reach out to Giraffe and see who would like to pair on it
