### ISSUE TITLE
COAM Validation and Testing

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-obps#259]
Purpose: obtain user feedback 

Activities
- [ ] User interview with ECCC if they have any user experience feedback or learnings from users that we can learn from, journey map emotive layer if possible
- [ ] Reach out to past research participants to see if they are using CATS
- [ ] Low-fidelity wireframe testing with business area 
- [ ] User interview with operators to validate the process flow and medium-fidelity wireframes user testing

**Comment by patrickisaac** [comment]
Closing this out - refers to bcgov/cas-coam#32 bcgov/cas-obps#298
