### ISSUE TITLE
COAM Glossary

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-obps#265]
Create a glossary of terminology used for COAM, so that the team can have a shared understanding of all the words used in COAM. 
[Link to the Glossary on MIRO](https://miro.com/app/board/uXjVNyzw5is=/?moveToWidget=3458764588252280257&cot=14) 
Purpose: Define commonly used terms like: Earned credits, offset credits, compliance report part 1 and 2

**Comment by zoeyli-46** [comment]
Hey @NicoleGovvy! I just remembered this ask from Andrea to create a glossary sheet of the terms used on COAM, made this ticket for it

**Comment by zoeyli-46** [comment]
@hannavovk Hey Hanna, could you review the [glossary sheet](https://miro.com/app/board/uXjVNyzw5is=/?moveToWidget=3458764588252280257&cot=14) and confirm if we can mark this ticket as done?

**Comment by hannavovk** [comment]
Thanks @zoeyli-46 and @NicoleGovvy! Reviewed and made some tweaks and comments. Also corrected "compliance account" sticky, but left the old one there in case you wanted to see the change (didn't record other tweaks as they were more minor). 
Accepting and closing the ticket. Thanks! 
(cc: @patriciarussellCAS )
