### ISSUE TITLE
Earned credits registry: proposed data fields

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-obps#270]
Purpose: Identify what data fields we need to collect from operators, and what data fields we can generate from on registration and reporting fields, for earned credits registry

Activities:
- [x] Develop initial list of data fields for the EC registry
- [x] Review with developers
- [x] Review with business area

Dependencies:
- blocked by bcgov/cas-coam#31

**Comment by NicoleGovvy** [comment]
Have list of data fields, reviewed by business and developers. Next step?

**Comment by NicoleGovvy** [comment]
Closing this ticket as we've finished the scope.
