### ISSUE TITLE
Refine COAM is / is not matrix

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-obps#273]
Refinement of the COAM is/is not matrix
Dependencies
- [x] Refinement is dependent on Business Area decisions on what is in scope versus what is not, namely how public information will be publicized, and whether compliance functionalities are in scope

**Comment by zoeyli-46** [comment]
can we move this to done? @hannavovk

**Comment by hannavovk** [comment]
Yes! It's done. Thank you @zoeyli-46!
