### ISSUE TITLE
Determine the form fields for holding account application

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-obps#275]
Operators must apply for a holding account, so that IRC can issue earned credits to their holding account. 

Activites
- [ ] Determine the fields required for the holding account application 
- [ ] Determine which fields can be pre-populated with data from registration

**Comment by zoeyli-46** [comment]
@NicoleGovvy just made this ticket, its for determining the fields for the holding account application that operators have to fill out (part of earned credits)

**Comment by NicoleGovvy** [comment]
Might repurpose this ticket to be requirements for applying for an account.

**Comment by NicoleGovvy** [comment]
This is part of ticket #270, closing for now.
