### ISSUE TITLE
COAM and earned credits data fields workshop with business area

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-obps#288]
- [x] Review the process map and how the data fields will correspond with the processes
- [x] Review the spreadsheet of data fields

**Comment by zoeyli-46** [comment]
@NicoleGovvy I think it could make sense to do the coam and earned credits data fields workshop in one session? or we could keep them separate!

**Comment by NicoleGovvy** [comment]
@zoeyli-46 yeah I think it might make sense to do it once, I will have a better sense once all the EC fields are done.

**Comment by NicoleGovvy** [comment]
@zoeyli-46 just noticing this ticket, do we still need it?

**Comment by zoeyli-46** [comment]
nope, they already reviewed it async and left their comments i will close this!
