### ISSUE TITLE
Reg\Facility - Pre-populate province field on add facility form

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-obps#325]
Given that I am on the Add Facility form,
When I am on the Province field under Facility Address section,
Then it is non-editable, and pre-filled with the value British Columbia 

![Image](https://github.com/user-attachments/assets/c8a0a7d9-1741-4f10-9831-d631ca578161)

Context: facilities can only be in British Columbia, so we shouldn't provide a dropdown or open field where they can enter any province other than BC

**Comment by patriciarussellCAS** [comment]
Hey @zoeyli-46 I think this should be in the registration repo, not OBPS, correct?

**Comment by zoeyli-46** [comment]
hi @patriciarussellCAS yes, I've actually archived this already and made a new ticket in registration :) its this one [#2269](https://github.com/bcgov/cas-registration/issues/2269)
