### ISSUE TITLE
Compile Metabase discovery feedback

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-obps#83]
Much was learned during the Metabase discovery! Let's bring those learnings together.

Acceptance Criteria:
- [x] Bring interview notes over to Miro
- [x] Bring survey results over to Miro
- [x] Pull out insights from interview notes
- [x] Pull out insights from survey results
- [x] Theme insights into patterns
- [x] Nan to review outcome asynchronously
- [x] Pull out core findings from research

**Comment by jaimiebutton** [comment]
Note - analysis is completed! @nanyangpro feel free to go in and review :) I'll also add the Attn:Nan label to test it out.

**Comment by nanyangpro** [comment]
Amazing! I'll review it today and let you know if there's additional feedback, thanks @jaimiebutton! It'll also be very helpful for laying down the internal discovery plan.

**Comment by nanyangpro** [comment]
Hi @jaimiebutton! I've finished reviewing the compiled findings from the Metabase Discovery with my comments/questions documented on the [frames](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764552937022315&cot=14). Wonderful work! Looking forward to discussing with you.
